# Generated by Django 5.0.7 on 2024-07-18 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merma', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categorias'},
        ),
    ]
